<a href="https://colab.research.google.com/github/saracsayed/saracsayed/blob/main/Data_Cleaning_Script.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning Script

# Set-up

In [ ]:
# Import packages necessary to run clean the data
import pandas as pd
import numpy as np
import scipy as sp
import glob
from pandas import DataFrame

In [ ]:
# Set working directory, we will need to be able to make this user friendly later
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# A test to make sure all the data files from Lauren made it to the drive
path = r'/content/drive/MyDrive/MP'
all_files= glob.glob(path + "/*.csv")
all_files

['/content/drive/MyDrive/MP/utility_block_scores_2018.csv',
 '/content/drive/MyDrive/MP/utility_rates_table_current.csv',
 '/content/drive/MyDrive/MP/utility_census_summary.csv',
 '/content/drive/MyDrive/MP/utility_service_scores_2018.csv',
 '/content/drive/MyDrive/MP/utility_cost_to_bill_current.csv',
 '/content/drive/MyDrive/MP/race_blockgroup_geoid_2018.csv',
 '/content/drive/MyDrive/MP/Hispanic.csv',
 '/content/drive/MyDrive/MP/NotHispanic.csv',
 '/content/drive/MyDrive/MP/water_system_summary.csv',
 '/content/drive/MyDrive/MP/Block_Scores_Demographic.csv',
 '/content/drive/MyDrive/MP/control_vars.csv',
 '/content/drive/MyDrive/MP/UrbanRural_2010.csv',
 '/content/drive/MyDrive/MP/Block.csv',
 '/content/drive/MyDrive/MP/Control_Variable_Table.csv']

In [ ]:
# Read in utility block scores csv
block_scores = pd.read_csv('/content/drive/MyDrive/MP/utility_block_scores_2018.csv')
block_scores.head()

          GEOID      pwsid utility_name  ...    PPI         burden   EPA
0  371999602002  01-00-010   Burnsville  ...  42.28  Moderate-High  2.31
1  371999602003  01-00-010   Burnsville  ...  42.28           High  3.92
2  371999602004  01-00-010   Burnsville  ...  42.28           High  2.75
3  371999603001  01-00-010   Burnsville  ...  40.63           High  3.78
4  371999603002  01-00-010   Burnsville  ...  40.63  Moderate-High  3.62

[5 rows x 15 columns]

In [ ]:
# Read in census block groups csv
census_blocks = pd.read_csv('/content/drive/MyDrive/MP/race_blockgroup_geoid_2018.csv')
census_blocks.head()

             County  Total Pop  White  Black  Native  Asian          GEOID
0   Alamance County        970     40    853       0       0  370010204005
1   Alamance County       1019    455    428       0       0  370010210003
2   Alamance County       1040    523    311       0      12  370010210001
3   Alamance County       1690    702    500      30       0  370010210002
4   Alamance County        424    256    122      46       0  370010202002

In [ ]:
## Read in labor hours data
labor_hours = pd.read_csv('/content/drive/MyDrive/MP/utility_service_scores_2018.csv')
labor_hours.head()

       pwsid                  utility_name  ...         burden  LaborHrs
0  01-00-010                    Burnsville  ...           High     11.96
1  01-02-010                  Taylorsville  ...  Moderate-High     12.21
2  01-02-020  Alexander County - Bethlehem  ...   Low-Moderate     10.29
3  01-03-010                        Sparta  ...           High     10.96
4  01-05-010                West Jefferson  ...  Moderate-High     14.11

[5 rows x 11 columns]

In [ ]:
# Read in rural/urban data
urban_rural = pd.read_csv('/content/drive/MyDrive/MP/UrbanRural_2010.csv')
urban_rural.head()

   Total  Urban  Inside UA  Inside UC  Rural         GEOID
0    468      0          0          0    468  370479307002
1    457      0          0          0    457  370479307003
2    495      0          0          0    495  370479307004
3    595      0          0          0    595  370479307005
4    522      0          0          0    522  370479308001

In [ ]:
# Join block score groups csv with labor hours csv
HBI_race = pd.merge(block_scores, labor_hours, left_on='pwsid', right_on='pwsid')
HBI_race.head()

          GEOID      pwsid utility_name_x  ...  WARI  burden_y  LaborHrs
0  371999602002  01-00-010     Burnsville  ...  4.49      High     11.96
1  371999602003  01-00-010     Burnsville  ...  4.49      High     11.96
2  371999602004  01-00-010     Burnsville  ...  4.49      High     11.96
3  371999603001  01-00-010     Burnsville  ...  4.49      High     11.96
4  371999603002  01-00-010     Burnsville  ...  4.49      High     11.96

[5 rows x 25 columns]

In [ ]:
## Read in ethnicity data
ethnicity_blocks = pd.read_csv('/content/drive/MyDrive/MP/NotHispanic.csv')
ethnicity_blocks.head(30)

              County  Total H  Total NH  ...  NH Other  NH Two or more         GEOID
0    Alamance County      970       893  ...         0               0  370010204005
1    Alamance County     1019       752  ...         0              80  370010210003
2    Alamance County     1040       841  ...         0              63  370010210001
3    Alamance County     1690      1236  ...         0              76  370010210002
4    Alamance County      424       306  ...         0               0  370010202002
5    Alamance County     1099       887  ...         0              47  370010202003
6    Alamance County     1146      1052  ...         0               5  370010202001
7    Alamance County      999       965  ...         0              15  370010213003
8    Alamance County     1273      1207  ...         2              16  370010213002
9    Alamance County     1380      1244  ...         0               0  370010216002
10   Alamance County     2150      2046  ...         0             109  370010216003
11   Alamance County     1792      1657  ...         0              31  370010214001
12   Alamance County      945       945  ...         0              15  370010214002
13   Alamance County     1414      1405  ...         0               0  370010215002
14   Alamance County     1138      1059  ...         0              20  370010215001
15   Alamance County     1695      1115  ...         0              31  370010204002
16   Alamance County     2866      2571  ...         0              40  370010204001
17   Alamance County     3062      2874  ...         0             108  370010216004
18   Alamance County      895       879  ...         0               0  370010212041
19   Alamance County     2685      2472  ...         0             220  370010212042
20   Alamance County     2764      1260  ...         0              54  370010203005
21   Alamance County     1078       474  ...         0               0  370010203001
22   Alamance County     1068       659  ...         0              28  370010203002
23   Alamance County     1882      1668  ...         0              35  370010212012
24   Alamance County     1224      1177  ...         0               8  370010212013
25   Alamance County     1136      1136  ...         0              31  370010218032
26   Alamance County     1522      1365  ...         0              71  370010219011
27   Alamance County     2005      1939  ...         0               9  370010219012
28   Alamance County     1034      1034  ...         0              18  370010219013
29   Alamance County     1665      1601  ...         0              57  370010219021

[30 rows x 11 columns]

## B. Data Modifications to Block Group Demographic Data

In [ ]:
## Calculate total number of hispanics 
ethnicity_blocks['TotalH'] = ethnicity_blocks['Total H']- ethnicity_blocks['Total NH']
ethnicity_blocks.head(3)

             County  Total H  Total NH  ...  NH Two or more         GEOID  TotalH
0   Alamance County      970       893  ...               0  370010204005      77
1   Alamance County     1019       752  ...              80  370010210003     267
2   Alamance County     1040       841  ...              63  370010210001     199

[3 rows x 12 columns]

In [ ]:
# Join ethnicity with race csv
race_ethnicity_merged= pd.merge(census_blocks, ethnicity_blocks, left_on='GEOID', right_on='GEOID')
race_ethnicity_merged.head()

           County_x  Total Pop  White  ...  NH Other  NH Two or more  TotalH
0   Alamance County        970     40  ...         0               0      77
1   Alamance County       1019    455  ...         0              80     267
2   Alamance County       1040    523  ...         0              63     199
3   Alamance County       1690    702  ...         0              76     454
4   Alamance County        424    256  ...         0               0     118

[5 rows x 18 columns]

In [ ]:
#Join fixed blockgroups with rural/urban
HBI_race_rural = pd.merge(HBI_race, urban_rural, left_on='GEOID', right_on='GEOID')
HBI_race_rural.head()

          GEOID      pwsid utility_name_x  ...  Inside UA  Inside UC  Rural
0  371999602002  01-00-010     Burnsville  ...          0          0    725
1  371999602003  01-00-010     Burnsville  ...          0          0    696
2  371999602004  01-00-010     Burnsville  ...          0          0    861
3  371999603001  01-00-010     Burnsville  ...          0          0   1411
4  371999603002  01-00-010     Burnsville  ...          0          0    879

[5 rows x 30 columns]

In [ ]:
# Delete redundant columns in race_ethnicity_merged csv
del HBI_race_rural['HBI_y']
del HBI_race_rural['PPI_y']
del HBI_race_rural['EPA_y']
del HBI_race_rural['burden_y']
del HBI_race_rural['utility_name_y']
HBI_race_rural.head()

          GEOID      pwsid utility_name_x  ...  Inside UA  Inside UC  Rural
0  371999602002  01-00-010     Burnsville  ...          0          0    725
1  371999602003  01-00-010     Burnsville  ...          0          0    696
2  371999602004  01-00-010     Burnsville  ...          0          0    861
3  371999603001  01-00-010     Burnsville  ...          0          0   1411
4  371999603002  01-00-010     Burnsville  ...          0          0    879

[5 rows x 25 columns]

In [ ]:
# Rename redundant names
HBI_labor = HBI_race_rural.rename(columns={'utility_name_x':'utility_name', 'HBI_x':'HBI','PPI_x':'PPI', 'burden_x':'burden', 'EPA_x':'EPA','utility_name_x':'utility_name'})
HBI_labor.head()

          GEOID      pwsid utility_name  ...  Inside UA  Inside UC  Rural
0  371999602002  01-00-010   Burnsville  ...          0          0    725
1  371999602003  01-00-010   Burnsville  ...          0          0    696
2  371999602004  01-00-010   Burnsville  ...          0          0    861
3  371999603001  01-00-010   Burnsville  ...          0          0   1411
4  371999603002  01-00-010   Burnsville  ...          0          0    879

[5 rows x 25 columns]

In [ ]:
# Join block score groups csv with census block groups csv
block_scores_merged= pd.merge(HBI_labor, race_ethnicity_merged, left_on='GEOID', right_on='GEOID')
block_scores_merged.head()

          GEOID      pwsid utility_name  ...  NH Other  NH Two or more  TotalH
0  371999602002  01-00-010   Burnsville  ...         0               0       0
1  371999602003  01-00-010   Burnsville  ...         0              33     176
2  371999602004  01-00-010   Burnsville  ...         0              19     126
3  371999603001  01-00-010   Burnsville  ...         0              32      29
4  371999603002  01-00-010   Burnsville  ...         0               0     160

[5 rows x 42 columns]

In [ ]:
#Create new columns to show percentages for each ethnic group and rural/urban population
block_scores_merged['Perc_White'] = (block_scores_merged['NH White']/ block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Black'] = (block_scores_merged['NH Black']/ block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Native'] = (block_scores_merged['NH Native']/ block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Asian'] = (block_scores_merged['NH Asian']/block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Pacific_Islander'] = (block_scores_merged['NH Pacific Islander']/block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Other'] = (block_scores_merged['NH Other']/block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Multi'] = (block_scores_merged['NH Two or more']/block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Hispanic'] = (block_scores_merged['TotalH']/block_scores_merged['Total Pop'])*100
block_scores_merged['Perc_Urban'] = (block_scores_merged['Urban']/block_scores_merged['Total'])*100
block_scores_merged['Perc_Rural'] = (block_scores_merged['Rural']/block_scores_merged['Total'])*100
block_scores_merged.head()

          GEOID      pwsid utility_name  ...  Perc_Hispanic  Perc_Urban  Perc_Rural
0  371999602002  01-00-010   Burnsville  ...       0.000000         0.0       100.0
1  371999602003  01-00-010   Burnsville  ...      13.739266         0.0       100.0
2  371999602004  01-00-010   Burnsville  ...       7.668898         0.0       100.0
3  371999603001  01-00-010   Burnsville  ...       1.685067         0.0       100.0
4  371999603002  01-00-010   Burnsville  ...      10.966415         0.0       100.0

[5 rows x 52 columns]

In [ ]:
# Remove dashes from the PWSID colummn ans strip the white space
block_scores_merged['pwsid'] = block_scores_merged['pwsid'].replace('-', '', regex=True)

In [ ]:
water_rates = pd.read_csv('/content/drive/MyDrive/MP/utility_rates_table_current.csv')

In [ ]:
# Remove dashes from the PWSID colummn ans strip the white space
water_rates['pwsid'] = water_rates['pwsid'].replace('-', '', regex=True)

In [ ]:
# Export final compiled demographic table for future use
block_scores_merged.to_csv('block_scores_geoid.csv')
water_rates.to_csv('water_rates.csv')

## Adding in PWS Data for NC

In [ ]:
# Read in adjusted block data (corrected for some columns) and convert pwsid object to int
block= pd.read_csv('/content/drive/MyDrive/MP/Block.csv')
block.head()
block['pwsid'].astype(str).astype(int)

0       100010
1       100010
2       100010
3       100010
4       100010
         ...
5799    392010
5800    392010
5801    392010
5802    392010
5803    392010
Name: pwsid, Length: 5804, dtype: int64

In [ ]:
block.head()

   Unnamed: 0         GEOID   pwsid  ... Perc_Hispanic  Perc_Urban  Perc_Rural
0           0  3.720000e+11  100010  ...      0.000000         0.0       100.0
1           1  3.720000e+11  100010  ...     13.739266         0.0       100.0
2           2  3.720000e+11  100010  ...      7.668898         0.0       100.0
3           3  3.720000e+11  100010  ...      1.685067         0.0       100.0
4           4  3.720000e+11  100010  ...     10.966415         0.0       100.0

[5 rows x 53 columns]

In [ ]:
# Read in NC PWS data to join service connections & system size to block score table
pws_system = pd.read_csv('/content/drive/MyDrive/MP/water_system_summary.csv', low_memory=False)
pws_system.head()

     PWSID  ... Service Connections Count
0   428415  ...                        20
1  1011055  ...                        19
2   145456  ...                        17
3   114577  ...                         2
4   156426  ...                         1

[5 rows x 7 columns]

In [ ]:
#Join block group data with PWS data to form final table of variables
cont_vars= pd.merge(block, pws_system, left_on='pwsid', right_on='PWSID')
cont_vars.to_csv('control_vars.csv')
cont_vars.head()

   Unnamed: 0         GEOID  ...  Population Served Count Service Connections Count
0           0  3.720000e+11  ...                    3,988                      1570
1           1  3.720000e+11  ...                    3,988                      1570
2           2  3.720000e+11  ...                    3,988                      1570
3           3  3.720000e+11  ...                    3,988                      1570
4           4  3.720000e+11  ...                    3,988                      1570

[5 rows x 60 columns]